
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:12.1'
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - ogma-network

  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4'
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ogma-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
    ogma-network:
        driver: bridge