
CREATE TABLE IF NOT EXISTS public.author
(
    id_author bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT author_pkey PRIMARY KEY (id_author)
    );

CREATE TABLE IF NOT EXISTS public.book
(
    id_book bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    depth real,
    height real,
    isbn_10 character varying(255) COLLATE pg_catalog."default",
    isbn_13 character varying(255) COLLATE pg_catalog."default",
    pages integer,
    price real,
    rating integer,
    release_date date,
    synopsis text COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    weight real,
    width real,
    id_publisher bigint,
    CONSTRAINT book_pkey PRIMARY KEY (id_book),
    CONSTRAINT ukcho13uw58fdxi26ivvrh1xuw1 UNIQUE (isbn_10),
    CONSTRAINT ukhlq8w38nafkwy8tol2l38epmo UNIQUE (isbn_13)
    );

CREATE TABLE IF NOT EXISTS public.book_author
(
    id_book bigint NOT NULL,
    id_author bigint NOT NULL,
    CONSTRAINT book_author_pkey PRIMARY KEY (id_book, id_author)
    );

CREATE TABLE IF NOT EXISTS public.book_genre
(
    id_book bigint NOT NULL,
    id_genre bigint NOT NULL,
    CONSTRAINT book_genre_pkey PRIMARY KEY (id_book, id_genre)
    );

CREATE TABLE IF NOT EXISTS public.book_lang
(
    id_book bigint NOT NULL,
    id_lang bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.book_literary_route
(
    id_book bigint NOT NULL,
    id_literary_route bigint NOT NULL,
    CONSTRAINT book_literary_route_pkey PRIMARY KEY (id_book, id_literary_route)
    );

CREATE TABLE IF NOT EXISTS public.comment
(
    id_comment bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content character varying(255) COLLATE pg_catalog."default",
    likes integer,
    id_post bigint,
    id_user bigint,
    CONSTRAINT comment_pkey PRIMARY KEY (id_comment)
    );

CREATE TABLE IF NOT EXISTS public.country
(
    id_country bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT country_pkey PRIMARY KEY (id_country)
    );

CREATE TABLE IF NOT EXISTS public.department
(
    id_department bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    name character varying(255) COLLATE pg_catalog."default",
    source character varying(255) COLLATE pg_catalog."default",
    id_province bigint,
    CONSTRAINT department_pkey PRIMARY KEY (id_department)
    );

CREATE TABLE IF NOT EXISTS public.exchange_offer
(
    id_exchange_offer bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    offer_date timestamp(6) without time zone,
    offered_post_id bigint,
    post_id bigint,
    user_id bigint,
    CONSTRAINT exchange_offer_pkey PRIMARY KEY (id_exchange_offer)
    );

CREATE TABLE IF NOT EXISTS public.genre
(
    id_genre bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT genre_pkey PRIMARY KEY (id_genre)
    );

CREATE TABLE IF NOT EXISTS public.image
(
    id_image bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    alt character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default",
    id_book bigint,
    CONSTRAINT image_pkey PRIMARY KEY (id_image)
    );

CREATE TABLE IF NOT EXISTS public.lang
(
    id_lang bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    abbr character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT lang_pkey PRIMARY KEY (id_lang)
    );

CREATE TABLE IF NOT EXISTS public.literary_route
(
    id_literary_route bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    rating integer,
    id_user bigint,
    CONSTRAINT literary_route_pkey PRIMARY KEY (id_literary_route)
    );

CREATE TABLE IF NOT EXISTS public.literary_route_book
(
    id_literary_route bigint NOT NULL,
    id_book bigint NOT NULL,
    CONSTRAINT literary_route_book_pkey PRIMARY KEY (id_literary_route, id_book)
    );

CREATE TABLE IF NOT EXISTS public.location
(
    id_location bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    name character varying(255) COLLATE pg_catalog."default",
    source character varying(255) COLLATE pg_catalog."default",
    id_province bigint,
    CONSTRAINT location_pkey PRIMARY KEY (id_location)
    );

CREATE TABLE IF NOT EXISTS public.municipality
(
    id_municipality bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    name character varying(255) COLLATE pg_catalog."default",
    source character varying(255) COLLATE pg_catalog."default",
    id_province bigint,
    CONSTRAINT municipality_pkey PRIMARY KEY (id_municipality)
    );

CREATE TABLE IF NOT EXISTS public.notification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    mailable boolean,
    message character varying(255) COLLATE pg_catalog."default",
    read boolean NOT NULL,
    received boolean NOT NULL,
    sent boolean NOT NULL,
    type character varying(255) COLLATE pg_catalog."default",
    id_user bigint,
    CONSTRAINT notification_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.post
(
    id_post bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    book_state character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    price character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    id_book bigint,
    id_user bigint,
    CONSTRAINT post_pkey PRIMARY KEY (id_post)
    );

CREATE TABLE IF NOT EXISTS public.post_desired_books
(
    post_id bigint NOT NULL,
    book_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.province
(
    id_province bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    iso_id character varying(255) COLLATE pg_catalog."default",
    iso_name character varying(255) COLLATE pg_catalog."default",
    latitude real,
    longitude real,
    name character varying(255) COLLATE pg_catalog."default",
    source character varying(255) COLLATE pg_catalog."default",
    id_country bigint,
    CONSTRAINT province_pkey PRIMARY KEY (id_province)
    );

CREATE TABLE IF NOT EXISTS public.publisher
(
    id_publisher bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT publisher_pkey PRIMARY KEY (id_publisher)
    );

CREATE TABLE IF NOT EXISTS public.review
(
    id_review bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    comment character varying(500) COLLATE pg_catalog."default",
    rating integer NOT NULL,
    id_book bigint,
    id_user bigint,
    CONSTRAINT review_pkey PRIMARY KEY (id_review)
    );

CREATE TABLE IF NOT EXISTS public.state
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    scope character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT state_pkey PRIMARY KEY (id),
    CONSTRAINT ukgcdtjhav66oejofov6qc2r7vi UNIQUE (name, scope)
    );

CREATE TABLE IF NOT EXISTS public.state_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    final_date timestamp(6) without time zone,
    initial_date timestamp(6) without time zone NOT NULL,
    id_book bigint,
    id_exchange_offer bigint,
    id_post bigint,
    id_state bigint NOT NULL,
    CONSTRAINT state_history_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    id_user bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    birth_date date,
    email character varying(255) COLLATE pg_catalog."default",
    genre character varying(255) COLLATE pg_catalog."default",
    hashed_password character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    user_site_name character varying(255) COLLATE pg_catalog."default",
    id_municipality bigint,
    id_province bigint,
    CONSTRAINT user_pkey PRIMARY KEY (id_user),
    CONSTRAINT ukhl4ga9r00rh51mdaf20hmnslt UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS public.user_posts
(
    user_id_user bigint NOT NULL,
    posts_id_post bigint NOT NULL,
    CONSTRAINT ukptxv781j0k5b7rx0c0yasaws UNIQUE (posts_id_post)
    );

ALTER TABLE IF EXISTS public.book
    ADD CONSTRAINT fksbbahnn1lbsccwb6cib9lj2r6 FOREIGN KEY (id_publisher)
    REFERENCES public.publisher (id_publisher) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_author
    ADD CONSTRAINT fkpwgpe60vfxwp9hdv10e7f186m FOREIGN KEY (id_author)
    REFERENCES public.author (id_author) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_author
    ADD CONSTRAINT fktgq2owtoxahamn884777o975j FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_genre
    ADD CONSTRAINT fk7ckoxtsinmmkro0n2kywfk91f FOREIGN KEY (id_genre)
    REFERENCES public.genre (id_genre) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_genre
    ADD CONSTRAINT fkccexx241jlwh3220h1vmk3876 FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_lang
    ADD CONSTRAINT fkpofj622ypli54i62fuqmrulnb FOREIGN KEY (id_lang)
    REFERENCES public.lang (id_lang) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_lang
    ADD CONSTRAINT fkq6j2v89adv58iyvklwy8vrej9 FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_literary_route
    ADD CONSTRAINT fkhvf7uu42rhfalsdjdak6syv75 FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_literary_route
    ADD CONSTRAINT fknd5tnxeoamm2h0lhp7bg3vjuq FOREIGN KEY (id_literary_route)
    REFERENCES public.literary_route (id_literary_route) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT fk1a78c2yh6591uvs75kcdnop1v FOREIGN KEY (id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT fk5d3jnie61rlb5an9r4hm9wq9n FOREIGN KEY (id_post)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.department
    ADD CONSTRAINT fk4l21f9dm9y0tkyuqyf58cyt8v FOREIGN KEY (id_province)
    REFERENCES public.province (id_province) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_offer
    ADD CONSTRAINT fk4vhswlkdfafmb7qjw5ec1c7lf FOREIGN KEY (offered_post_id)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_offer
    ADD CONSTRAINT fkei42ipj1iyrphc68ccyvmc5y2 FOREIGN KEY (post_id)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_offer
    ADD CONSTRAINT fkix7pgyb7kn6fnwfuicdbh2vp5 FOREIGN KEY (user_id)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.image
    ADD CONSTRAINT fkfx3b7c01e7d3iw8n6s7y9lsi5 FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.literary_route
    ADD CONSTRAINT fk43o2dptl8uwwrpyq8dmujit5 FOREIGN KEY (id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.literary_route_book
    ADD CONSTRAINT fk8kdvr99xdqsffijypf50bntff FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.literary_route_book
    ADD CONSTRAINT fkc3g7fcjn7g9b7ll3xqcht7334 FOREIGN KEY (id_literary_route)
    REFERENCES public.literary_route (id_literary_route) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.location
    ADD CONSTRAINT fk8uqtm89fas5o4iu7u8sklclnt FOREIGN KEY (id_province)
    REFERENCES public.province (id_province) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.municipality
    ADD CONSTRAINT fkoxnevbfu7sbn7psw5469v92w2 FOREIGN KEY (id_province)
    REFERENCES public.province (id_province) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notification
    ADD CONSTRAINT fk7jarxljg5m0iqjcx8et9i80w6 FOREIGN KEY (id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT fkffnpiv7w01dw0ms5isp5t0bos FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT fksymew3m2ky806oti63uvv7l62 FOREIGN KEY (id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post_desired_books
    ADD CONSTRAINT fkhysvi6n9syu0pliaow8v8n63k FOREIGN KEY (post_id)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post_desired_books
    ADD CONSTRAINT fkp9a24fbwshspldex6w64u5vcn FOREIGN KEY (book_id)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.province
    ADD CONSTRAINT fk98v797u71n5gvqa6h8hd55lio FOREIGN KEY (id_country)
    REFERENCES public.country (id_country) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk4pg8e54fsaswy3hv8f3uuy381 FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fkajlelxnv9s4f9abfii7erj0m7 FOREIGN KEY (id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.state_history
    ADD CONSTRAINT fk4mo9ar9xavk2xy1xnvf0m992s FOREIGN KEY (id_state)
    REFERENCES public.state (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.state_history
    ADD CONSTRAINT fk73lywv5exbfyr8ldsve17vc9o FOREIGN KEY (id_post)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.state_history
    ADD CONSTRAINT fkcvf04a7tfvgdnaqpne97u93wl FOREIGN KEY (id_book)
    REFERENCES public.book (id_book) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.state_history
    ADD CONSTRAINT fkksoahp94su8843hlnpd8dnxu6 FOREIGN KEY (id_exchange_offer)
    REFERENCES public.exchange_offer (id_exchange_offer) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT fkgle0v5l3pronr6xtgn1p0jkn0 FOREIGN KEY (id_municipality)
    REFERENCES public.municipality (id_municipality) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT fkku74sjq9hi7kh8x7k9t6l5x0p FOREIGN KEY (id_province)
    REFERENCES public.province (id_province) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_posts
    ADD CONSTRAINT fkaqsipmu2imixvg9c30nv64lhp FOREIGN KEY (user_id_user)
    REFERENCES public."user" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_posts
    ADD CONSTRAINT fkfe5wyxe3i112yqt6s64xg4mfo FOREIGN KEY (posts_id_post)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukptxv781j0k5b7rx0c0yasaws
    ON public.user_posts(posts_id_post);
