INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aaron Hirsh', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Savanna Welles', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard North Patterson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Philip K. Dick', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gustave Le Rouge', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gustave Guitton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Louise Michel', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard F. Burton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles E Gannon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jack McDevitt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Javier Martínez Reverte', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Patrick Rothfuss', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gemma Files', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles Soule', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Victoria Schwab', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elise Kova', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Olivie Blake', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pedro Torrijos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brandon Sanderson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ted Chiang', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Arturo González-Campos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cocúa Ripoll', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Emilia Pardo Bazán (Condesa de)', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Walter Tevis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alastair Bonnett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Juan Claudio de Ramón', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nachter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('La drama queen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mariana Enriquez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Daniel Wallace', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. R. R. Tolkien', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Jordan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carlos Sisí', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephen King', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Chizmar', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Francisco Javier Arellano Selma', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Antonio Cabrera Perera', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nnedi Okorafor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Shirley Jackson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alfredo Álamo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andrzej Sapkowski', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('TED. CHIANG', NOW(), NOW());
