INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alastair Boyd', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Terry Goodkind', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alex Barclay', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('George R. R. Martin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alan Moorehead', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sir Ernest Shackleton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Burton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sir Richard Francis Burton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Olaudah Equiano', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anton Chekov', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lady Catherine Macartney', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kate Hopkins', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mark Billingham', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pankaj Mishra', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Connolly', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edward Rowe Snow', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Wendy Northcutt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John O''Farrell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gordon West', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Luanne Rice', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tom Pawlik', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Amber Anthony', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('William S. Burroughs', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Raymond E. Feist', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Steven Scott Phillips', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Margo Lanagan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Paul Haines', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Terry Dowling', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Leo Nix', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rachel Watts', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cindy Moussi', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Annette Freeman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ashley R Scott', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Braxton Stewart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Edwards, 3rd', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Delores Edwards', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Donita Edwards', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Melissa Stetten', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tomi Ungerer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bruce Parry', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Hugh Thomson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bob Rakoczy', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Larry Pletcher', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lorene Jackson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rick Steelhammer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mary Lynn Blanks', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sarah Pagliasotti', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Susan Finch', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Julie A Hill and Associates LLC', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Susan Campbell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ray Bendici', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bill Heald', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kent Priestley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jon Elliston', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jim Bradley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cheryl Johnson Huban', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pam van Drimlen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eric Jones', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bill Scheller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kay Scheller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Paris Permenter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Bigley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Peter Allison', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kevin Revolinski', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Beth Kanter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Joseph Adams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('George Mann', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Larry Niven', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edward M. Lerner', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. A. Pitts', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. E. Mooney', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bill Fawcett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Melanie Rawn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Karl Schroeder', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('F. Paul Wilson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('L. E. Modesitt, Jr.', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John C. Wright', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dan Krokos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('C.T. Adams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cathy Clamp', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephen Hunt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brian Lumley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mary Robinette Kowal', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Melissa F. Olson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elizabeth Haydon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Willow Palecek', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andy Remic', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Orson Scott Card', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James O''Neal', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sara Douglass', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ben Bova', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Hood', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('R. A. Salvatore', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John David Smith', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Contemporary Books', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Contemporary Staff', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mary Huse Eastman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Miller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kristen Miller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jeff Noon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Boris Arnov', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David A. Crossman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Virginia L. Thorndike', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alice Arlen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elizabeth Peavey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Steven R. Pinkham', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Craig Fry', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Matthew Crampton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David Peutherer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Max Scratchmann', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Michaelson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Murdoch', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eric J Campbell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rae Lori', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Judith T Lambert', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Don DeBon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jay Cannon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Harry Connolly', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Derrien Relyea', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Scott J Robinson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Scott J. Robinson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Isaac Hooke', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Russell Hannon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ebony McKenna', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Johnny Welsh', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Austin Dragon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elizabeth Lee Sorrell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('G. S. Jennsen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('C. M. Bacon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rodrigo de Toledo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nan Kilmer Baker', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephanie Osborn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sue Raymond', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Laurie McAndish King', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Douglas J. Wood', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Deanna Cooner', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Dennehy', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Akers', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rebecca Chastain', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joanna Spathis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kerri Kennedy', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lani Longshore', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ann Anastasio', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tami Hoag', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jennifer Wilson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rosecrans Baldwin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aaron Hirsh', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gillian Fetlocks', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mike Haskins', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Savanna Welles', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard North Patterson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Larry Pounds', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ben Pounds', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mathias Eichler', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Douglas Scott', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Colleen Hancock', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sean Hancock', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Terence Hayes', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Abi G. Douglas', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gaja J. Kos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Boris Kos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sam Joyce', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Oliver McNeil', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Muhammad Vandestra', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Matthew Broyles', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rosie B. Davies', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Graham Moore', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('George MacDonald', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('A. R. Morlan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Christopher Morley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Francisco Toledo Rosenfield', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Laura Diaz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carlos Granell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joaquin Huerta', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ruizhi Chen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Donald Patrick Albert', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('G. Rebecca Dobbs', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Crais', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ilaria Tuti', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tim MacGabhann', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lola Albion', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Allan Cole', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Moss M. D.', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Moss, M.D.', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Manny Gutierrez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brett Wortham', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Randi Minetor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Donald Pfitzer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jimmy Jacobs', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James L. Hoffman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stewart M. Green', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mike Bezemek', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Janice McDonald', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Scott Williams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mark R. Weinberger', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Callum Clegg', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Xtina Marie', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('H. G. Wells', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Fritz Leiber', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edgar Rice Burroughs', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Harry Harrison', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Poul Anderson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edgar Pangborn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Keith Laumer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('C. M. Kornbluth', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alan E. Nourse', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('William Tenn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Hal Clement', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Murray Leinster', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Marion Zimmer Bradley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Frederik Pohl', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andre Norton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Philip K. Dick', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('F. Scott Fitzgerald', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('H. P. Lovecraft', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David Lindsay', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Knowles', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jacob Burkhardt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rainer Maria Rilke', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lucy Maud Montgomery', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jerome K Jerome', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John W. Jr. Campbell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pandian Vasant', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kalaivanthan M.', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anastasia Paraskou', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Babu P. George', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Hatem El-Gohary', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David John Edwards', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Riyad Eid', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Luis Martinez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('S. Dorman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Armond Boudreaux', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Corey Latta', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Baby Professor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Patrick M. Reynolds', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sophia Dembling', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Daniel J. Gelo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Wayne Pate', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('William Alexander', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Les Weatheritt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joseph Campbell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David J. Eicher', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jim Burnett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stanley Stewart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Randy White', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Maria Giura', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James P. Hogan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edward Bulwer Lytton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jerome K. Jerome', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Daniel Defoe', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('William James', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nalin Sharda', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Victoria Doudera', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Leigh Brackett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Diana Pharaoh Francis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Albert Bleunard', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Georges Pellerin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tom Minder', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anthony Boucher', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Henri Bergson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('M. Charles Doughty', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kevin J. Anderson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gregory Benford', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jody Lynn Nye', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jason Hess', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('K. W. Kirkland', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alexis A. Gilliland', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Heather Lende', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ruth Plumly Thompson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Adam Nicolai', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('A. Shockey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('George Washington', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Moncure D. Conway', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anthony Pioppi', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Fred Stone', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dino Caruso', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Harambee K. Grey-Sun', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andrew Grey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aea Kimlin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Necmiye Karatas', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nur Emine Koç', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jonathan Maberry', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tim Waggoner', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mort Castle', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brian Travilla', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Speedy Publishing LLC', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Third Cousins', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('@Journals Notebooks', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lerone Bennett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kat Williams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nathan Hopp', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lyn Drummond', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Amelia Thomas', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Allan Weiss', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Claire McCague', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jack Castle', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Maria Depenweiller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eve Langlais', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ravin Tija Maurice', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dan Andriacco', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kieran McMullen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Suyi Davies Okungbowa', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lewis Carroll', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bernard Louis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Christian Boustead', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Colin Coles', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Steve Williams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Heidi Perks', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Victor Pelevin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Peter Fleming', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jenny Diski', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andrew Lang', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard F. Burton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Shafaat Ahmad Khan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dave Walker', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dave O''Neil', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tony Wheeler', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lisa Mol', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Troy Sternberg', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Janet Neel', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charlotte Perkins Gilman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Peter John', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Professor of Political Science and Public Policy Peter John', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David R Stokes', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Spencer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. F. Penn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bec McMaster', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Hedley Derenzie', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Demelza Carlton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jim McPherson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elisabeth Graves', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jane Jenkins Herlong', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joe McKinney', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Genevieve Jack', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rachael Lavin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lucas Mangum', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles E Gannon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jack McDevitt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Tricia Mingerink', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pamela J. Morton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. Steven Young', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Arthur Machen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jay Artale', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gwendolyn Kiste', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ed Kurtz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bracken MacLeod', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joshua Robertson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Susan Kuchinskas', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ward Parker', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joy Ross Davis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('M. R. Mathias', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lauren Jankowski', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('MacLeod Kate', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John G. Hartness', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Shay Roberts', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Catie Rhodes', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dayle Grande Herstik', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jacob Grimm', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Wilhelm Grimm', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('A. M. Shah', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. W. Reed', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James L. Snyder', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('R. W. K. Clark', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bobbi Holmes', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anna J McIntyre', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Anna J McIntye', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elizabeth Mackey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Polyglot Language Learning', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Martin Kennedy', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Fred Hoon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Glynn Stewart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Hs Paisley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gabriel Blake', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Izumi Earl', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('SHANI. STRUTHERS', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Diana L. Paxson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. C. Wright', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephen King', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Philip Kindred Dick', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Georges Simenon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Terry Pratchett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Ronald Reuel Tolkien', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pierre Boulle', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert James Waller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Liviu Rebreanu', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Guy Rachet', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David Roberts', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. C. Simon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ramon Xirau', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Patrick Rothfuss', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bridget Collins', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mavi Doñate', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('PATRICK ROTHFUSS', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robin Cook', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Isaac Asimov', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jean Teulé', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. J. Benítez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dominique Lapierre', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joe Abercrombie', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Daniel Abraham', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David W. Ball', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Paul Cornell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Phyllis Eisenstein', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gillian Flynn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Neil Gaiman', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joe R. Lansdale', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Scott Lynch', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Matt Hugues', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Garth Nix', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cherie Priest', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Steven Saylor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Michael Swanwick', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lisa Tuttle', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carrie Vaughn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Walter Jon Williams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brian McClellan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jo Walton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sara Escudero Sánchez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eva Amuedo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rubén Bellés', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Noelia Gema Carmona Fernández', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mila Espigar', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles Soule', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Wyndham', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Howard Phillips Lovecraft', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edgar Allan Poe', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bram Stoker', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Paolo Bacigalupi', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Katy Rose Pool', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Victoria Schwab', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('NAOMI. NOVIK', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Naomi Novik', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elise Kova', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Olivie Blake', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Martín Caparrós', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carl Zitelmann', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ray Bradbury', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Pedro Torrijos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Brandon Sanderson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Steven Erikson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Frank Herbert', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ted Chiang', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Grady Hendrix', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles-Ferdinand Ramuz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Thomas Baudelet Olde Heuvelt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('José Godoy Pérez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andy Weir', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Octavia E. Butler', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Arturo González-Campos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sara Gutiérrez (Gutiérrez Torre)', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jorge de Cascante', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Cocúa Ripoll', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Susanna Clarke', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Emilia Pardo Bazán (Condesa de)', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Fernanda García Lao', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alix E. Harrow', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Walter Tevis', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ursula K. Le Guin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alastair Bonnett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Juan Claudio de Ramón', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Abraham Merritt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Javier Martín Lalanda', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Virgil Finlay', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Thor Heyerdahl', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('María Borotau', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Natalie Couilloud', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bernard Moitessier', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Julio Villar', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rudy Rucker', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Theodore Sturgeon', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Holdstock', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Iain Banks', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Kahn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert E. Howard', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nachter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mariana Enriquez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Agnès Michaux', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gordon Dahlquist', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Heinrich Heine', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Miquel Barceló', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jim Lovell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Drew Magary', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. R. R. Tolkien', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Jordan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Oliver Bowden', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Silvia Moreno-Garcia', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Kim Stanley Robinson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carlos Sisí', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Italo Calvino', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('William Gibson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. G. Ballard', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Catherine Banner', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dan Abnett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('L. Sprague De Camp', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Karl Edward Wagner', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Mike Lee', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Howe', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('AA. VV.', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jean Rabe', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eric S. Nylund', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Graham McNeill', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('C. S. Goto', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ben Counter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sandy Mitchell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Chris Roberson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joe Schreiber', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nick Kyme', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Varios autores', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Swallow', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Alan Merrett', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('PABLO REY BERRI', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jennifer Heath', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Xavier Narro i Salvans', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('James Corey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Dan Simmons', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Johann Wolfgang von Goethe', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Luis Pedro Peña Santiago', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Josep Iglésies', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Joanna Russ', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Suzette Haden Elgin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Arthur Charles Clarke', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gentry Lee', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Daniel J. Boorstin', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Charles Richard Vaughan', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Jaime Cobreros Aguirre', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sir Arthur Conan Doyle', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Ford', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carlos Pascual', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Les Daniels', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephen R. Lawhead', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ciclo pendragón', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gemma Gallart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David Day', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert Silverberg', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Peter Matthiessen', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elke Herms-Bohnhoff', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Josefina Castellví', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Víctor Alperi', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('J. L. Rodríguez Plasencia', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Elena Mampel González', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Neus Escandell Tur', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Antonio de Andrade', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ruy González de Clavijo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Eric Frank Russell', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Roberto Aguilera', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Juan José Plans', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Àngel Rifà Ros', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lauren Beukes', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Enric González', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Ken Liu', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Richard Chizmar', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('E. K. Johnston', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Drew Karpyshyn', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('David Henry Keller', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Antonio Cabrera Perera', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Santiago Tejedor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('A.C.H. Smith', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aleksandr Bogdanov', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gustave Flaubert', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Chema Rodríguez', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Carlos Villalba Imedio', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Simonetta Agnello Hornby', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Javier Más', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('V. Javier Mas Torrecillas', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nnedi Okorafor', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Shirley Jackson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('José Ramón Alonso de la Torre', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Diostuitero', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('José Luis Clemente', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Andrzej Sapkowski', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Teresa Pàmies', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('H.P. Lovecraft', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Rory Stewart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Xosé Miranda Ruiz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Xavier Miranda Ruiz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Zane Grey', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Lionel C. Dunsterville', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Theodore Roosevelt', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sean Stewart', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Robert A. Heinlein', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Scott Nicholson', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Stephen Baxter', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Crowley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Soriano Gutiérrez, Ignacio', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Llorenç Soldevila', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('L. Permanyer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Basilio Villarino', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Nefer Williams', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Fabienne Verdier', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bonabentura Ubach i Medir', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bonaventura Ubach', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Isaac . . . [et al. ] Asimov', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('ANDRZEJ. SAPKOWSKI', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('TED. CHIANG', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Felix de Azara', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gotzon Mantuliz Dudagoitia', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Gorka Larrumbide Seco', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('André Gide', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Homer', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Asian Development Bank', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Manoj Sharma', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Melissa Howell Alipalo', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Geraldine Edith Mitton', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('John Cunningham Geikie', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sir Walter Besant', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Edgar G. Daylight', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Peter Naur', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Sebastian Nanz', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Augusto Roa Bastos', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aurora Merino', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Aldous Leonard Huxley', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Theodor W. Adorno', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Godfrey Mwakikagile', NOW(), NOW());
INSERT INTO public.author (name, created_at, updated_at) VALUES ('Bankole Kamara Taylor', NOW(), NOW());
