INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('HarperCollins UK', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('HarperCollins', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Voyager', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Penguin UK', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('St. Martin''s Griffin', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Little Brown GBR', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Pan Macmillan', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Hodder Paperbacks', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Outlet', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Penguin', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Random House', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Corgi', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Bantam', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Mo Dog', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Street Smart ERP Publications', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Keith Stevenson', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('135press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Blurb', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Phaidon Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Falcon Guides', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Falcon Press Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Curiosities Series', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Globe Pequot Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Fun with the Family Series', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Office the Beaten Path Series', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Globe Pequot', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Day Trips Series', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Macmillan', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Tor Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Starscape', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Tor Romance', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('St. Martin''s Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Tordotcom', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('McGill-Queen''s Press - MQUP', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Univ of North Carolina Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Contemporary Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Chronicle Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('National Geographic Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Taylor Trade Publications', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Poison Pixie Limited', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Ashen Twilight', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Dbdigital', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Jay Cannon', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Cmb Fiction', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Studio Neurondiva', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Stones in Clay', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Picador', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Digireads.com Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Wildside Press LLC', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Pomona Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Palibrio', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Weidenfeld & Nicolson', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('iUniverse', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Life Rich Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Touring History', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Day Trips from Washington, D.C', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Scenic Driving', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Haunted', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Rowman & Littlefield Publishers', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Balboa Press Au', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Hellbound Books Publishing LLC', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('SMK Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Business Science Reference', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('IGI Global, Business Science Reference', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Resource Publications (CA)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Wipf and Stock Publishers', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Baby Professor (Education Kids)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Algonquin Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('New World Library', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Lyons Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('VIA Folios', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Arc Manor LLC', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Serenity Publishers', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Cosimo, Inc.', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('IGI Global Snippet', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Bell Bridge Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Hollywood Comics', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Wordfire Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Dragoneye Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Empty-Grave Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Booklocker.Com Incorporated', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Gray Rabbit Publications', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Hyperverse Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Dreamspinner Press LLC', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Iau Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Speedy Publishing Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Third Cousins', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('@Journals Notebooks', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('www.bnpublishing.com', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('EDGE Science Fiction and Fantasy Publishing, Incorporated', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('MX Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Abaddon', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Paragon Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Arrow', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Canongate Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Birlinn Publishers', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Virago Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Obscure Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('READ BOOKS', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Canterbury Press Norwich', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Nero', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('John Spencer Writes', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Curl Up Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Xoum Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Phantacea Phase Two', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Iron Stream Media', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Espec Books', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Bhc Press/Windswept', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Animus Ferrum Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Strategic Book Publishing & Rights Agency', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Haunting Danielle', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Language Mastery Publishing', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Xlibris Us', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Jsunley Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Gallimard Education', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Livre de Poche', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('LGF/Le Livre de Poche', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('10/18', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Fleuve Noir', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Pocket (FR)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Biblioteca de La Imagen', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Cenzontle', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Plaza & Janes Editories Sa', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('PLAZA & JANES', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('BRUGUERA (SELLO)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Grupo Planeta (GBS)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Clásicos Ilustrados', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Urano', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Umbriel', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Ediciones Urano', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Malpaso Editorial', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Batiscafo', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Siruela', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Anagrama', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Minotauro Ediciones Avd', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('TimunMas', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Timun Mas', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('EDB FICCION', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Nova', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Editorial Critica (Grupo Editorial Grijalbo)', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Ediciones Encuentro, S.A.', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Junta de Castilla y Leon Consejer Eria', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Edicions Universitat Barcelona', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Cossetània Edicions', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Ediciones Brontes', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Editorial UOC', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Nocturna', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Marlex Editorial', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Ediciones GATOPARDO SLU', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Masesmas', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('LA Factoria De Ideas', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Entrelineas Editores', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Linkgua Ediciones Sl', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Salamandra', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('L''Abadia de Montserrat', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Linkgua', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Grupo Planeta Spain', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Asian Development Bank', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('Alpha Edition', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('New Africa Press', NOW(), NOW());
INSERT INTO public.publisher (name, created_at, updated_at) VALUES ('New Africa Pres', NOW(), NOW());
