INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Andalusia (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Friendship', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sin categoría', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Australia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Antarctica', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Biography & Autobiography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Russia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Diplomats'' spouses', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cooking', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Detective and mystery stories', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Social Science', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Boys', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Disasters', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Humor', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('History', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Majorca (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Computers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Self-Help', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Amazon River Region', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Explorers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sports & Recreation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mountain biking', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Curiosities and wonders', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Children', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Family recreation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New York (State)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Connecticut', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Berkshire Hills (Mass.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cape Cod (Mass.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New Jersey', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Automobile travel', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Patagonia (Argentina and Chile)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Washington (D.C.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Juvenile Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fairy tales', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Atlantic Coast (Me.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Maine', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Geography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('California, Southern', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Travel', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Comics & Graphic Novels', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Political participation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Nature', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Children''s stories', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Geographic information systems', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Electronic books', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Religion', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fredericksburg (Va.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Atlanta Metropolitan Area (Ga.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Georgia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Minnesota', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Poetry', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Literary Collections', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Hospitality industry', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Human reproductive technology', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Pilgrims and pilgrimages', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Juvenile Nonfiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Literary Criticism', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('TRAVEL', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Health & Fitness', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Asia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Adventure and adventurers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Business & Economics', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Body, Mind & Spirit', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Reference', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Golf courses', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Blizzards', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Technology & Engineering', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Music', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Australians', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Leisure', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('China', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New Zealand', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Deserts', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Horror tales, American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Young Adult Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Doppelgängers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Foreign Language Study', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Extraterrestrial beings', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Maigret, Jules (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Baggins, Frodo (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Apes', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Art', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Education', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Robots', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Jerusalem', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Betrayal', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mars (Planet)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Philosophy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Young Adult Nonfiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Detective and mystery stories, Spanish', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('American fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy fiction, American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fatuhiva Island', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Boats and boating', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Discworld (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Space warfare', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Conan (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sexism', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Space vehicle accidents', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Families', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mythology, Celtic', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Black Virgins', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Catalonia (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Civilization', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Vampires', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Shipwrecks', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Pastoral systems', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Adult children', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Spain', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Madrid (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Arts', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Death', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Businessmen', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Iraq', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('City planning', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Paraguay', NOW(), NOW());
