INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Andalusia (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Asia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Friendship', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sin categoría', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Travel', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Abyssinian Expedition, 1867-1868', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Australia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Healers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Reference', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Nature', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Antarctica', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Best sellers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Biography & Autobiography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Russia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Art', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Voyages and travels', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Khiva (Uzbekistan)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Diplomats'' spouses', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Egypt', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cooking', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Amazon River Region', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Detective and mystery stories', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Murderers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Business & Economics', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Social Science', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Boys', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sports & Recreation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Spain', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('History', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Dracula, Count (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Columbia River', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Lord of the rings', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Disasters', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Religion', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Humor', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Majorca (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Papua New Guinea', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Computers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Self-Help', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cambodia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Adventure and adventurers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mountaineering expeditions', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Jamaica', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Explorers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Westport (Conn.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('American wit and humor', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mountain biking', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Curiosities and wonders', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Children', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Family recreation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New York (State)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Connecticut', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Berkshire Hills (Mass.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cape Cod (Mass.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New Jersey', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Automobile travel', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Patagonia (Argentina and Chile)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Washington (D.C.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Juvenile Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fairy tales', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cairo (Egypt)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Atlantic Coast (Me.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Maine', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Geography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('California, Southern', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Comics & Graphic Novels', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Political participation', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Children''s stories', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Geographic information systems', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Electronic books', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fredericksburg (Va.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Atlanta Metropolitan Area (Ga.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Georgia', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Minnesota', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Poetry', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Literary Collections', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Hospitality industry', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Human reproductive technology', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Pilgrims and pilgrimages', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Juvenile Nonfiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Literary Criticism', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('TRAVEL', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Health & Fitness', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('England', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Body, Mind & Spirit', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Golf courses', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Blizzards', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Technology & Engineering', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Music', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Australians', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Leisure', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Adventure travel', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mountaineering', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Discoveries in geography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Rock climbing', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('China', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Terror', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Horror psicológico', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasía', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasía épica', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Romance', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Romantasy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasía romántica', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('New Zealand', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Prague (Czech Republic)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cypher, Richard (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Italy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Deserts', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Horror tales, American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Young Adult Fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Doppelgängers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Foreign Language Study', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Extraterrestrial beings', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Amazon River', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Description de l''Egypte', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Guadeloupe', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Authors, French', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Maigret, Jules (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Baggins, Frodo (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Apes', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Bicycle touring', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('America', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Photography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('American fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Discworld (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Education', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Dune (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Death', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Robots', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Apostles', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Christian fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Córdoba (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Jerusalem', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Betrayal', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mars (Planet)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Philosophy', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Authors, Cuban', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Young Adult Nonfiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Detective and mystery stories, Spanish', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Spanish language materials', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fantasy fiction, American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Authors, Catalan', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Lima (Peru)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Alcarria Plateau (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Spaniards', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mothers and daughters', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Horror tales', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Misiones indígenas', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Midget submarines', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fatuhiva Island', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Changabang Mountain (India)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Amazon River Valley', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mayas', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Easter Island', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Boats and boating', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Tibet Autonomous Region (China)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Ballooning', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science fiction, Latin American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science fiction, American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Historical fiction', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Murder', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science fiction, English', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Space warfare', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Conan (Fictitious character)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Christian pilgrims and pilgrimages', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Beijing (China)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Almería (Spain : Province)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Sexism', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Architecture, Renaissance', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Guadarrama Mountains (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Manchester (England)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Shipwrecks', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Botany', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mormons', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Space vehicle accidents', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Plants', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Love', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Spanish literature', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Families', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Language file', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Kings and rulers', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Earthsea (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('British', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Massachusetts', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Aztecs', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mythology, Celtic', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Diplomatic and consular service, Spanish', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Alternative histories (Fiction), American', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Espana', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Black Virgins', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Catalonia (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Civilization', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Artists'' books', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Asia, Central', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Jesus prayer', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Statue of Liberty (New York, N.Y.)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Vampires', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Death Gate Universe (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Dragons', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Roads', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Psychology', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Science', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Pastoral systems', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Political satire, Spanish', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Cold regions', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Islam', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Invective', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Adult children', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Hiking', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Laciana Region (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Middle Earth (Imaginary place)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Architecture', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Horses, Fossil', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Turkey', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Damascus (Syria)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Everest, Mount (China and Nepal)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Christian biography', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Valencia (Spain : Province)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Africa', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Modernism (Literature)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fugitive slaves', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Assassins', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Madrid (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Holocaust, Jewish (1939-1945)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Short stories, Spanish', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Seville (Spain)', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Expedición Marítima de la Vacuna', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Arts', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Literary landmarks', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Missions', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Africa, Southern', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Fourth dimension', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Businessmen', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Peruvian literature', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Iraq', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('City planning', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Paraguay', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Argentine wit and humor, Pictorial', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Chile', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Composers, Italian', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Mexican poetry', NOW(), NOW());
INSERT INTO public.genre (name, created_at, updated_at) VALUES ('Popular literature', NOW(), NOW());
