INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=t4onnwEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Telling Our Way to the Sea', 1);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=t4onnwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Telling Our Way to the Sea', 1);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/11/9781250050311.jpg', 'Telling Our Way to the Sea', 1);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OkELkAEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'When the Night Whispers', 2);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OkELkAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'When the Night Whispers', 2);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/26/9781250122926.jpg', 'When the Night Whispers', 2);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=MMCbDAEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'The Race', 3);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=MMCbDAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The Race', 3);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/75/9781250123275.jpg', 'The Race', 3);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=EWzVtQEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Fantastic Stories Present the Philip K. Dick Super Pack', 4);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=EWzVtQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Fantastic Stories Present the Philip K. Dick Super Pack', 4);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/21/9781515422921.jpg', 'Fantastic Stories Present the Philip K. Dick Super Pack', 4);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=kY44LgEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'The Dominion of the World', 5);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=kY44LgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The Dominion of the World', 5);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/75/9781612270975.jpg', 'The Dominion of the World', 5);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=cAy0MQEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'The Human Microbes', 6);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=cAy0MQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The Human Microbes', 6);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/63/9781612271163.jpg', 'The Human Microbes', 6);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=IIQtmhHS9LEC&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'The Land of Midian (North-Western Arabia) Volume I', 7);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=IIQtmhHS9LEC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The Land of Midian (North-Western Arabia) Volume I', 7);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/28/9781846645228.jpg', 'The Land of Midian (North-Western Arabia) Volume I', 7);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=gUlfvgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'The Best of Defending the Future', 8);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=gUlfvgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'The Best of Defending the Future', 8);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/83/9781942990383.jpg', 'The Best of Defending the Future', 8);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/45/9788401027345.jpg', 'La frontera invisible', 9);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=WURvPgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El nombre del viento', 10);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=WURvPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El nombre del viento', 10);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/08/9788401337208.jpg', 'El nombre del viento', 10);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=smq5zwEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Canta Irlanda', 11);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=smq5zwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Canta Irlanda', 11);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/73/9788401346873.jpg', 'Canta Irlanda', 11);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/77/9788411121477.jpg', 'Star Wars Las guerras de los cazarrecompensas no 2/3 Nave esclava (novela)', 12);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/06/9788411158206.jpg', 'El psicólogo de Dios', 13);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/30/9788412281330.jpg', 'Esto no es para vosotros', 14);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/66/9788413416366.jpg', 'Luz de los Jedi', 15);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=qWdWzQEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'La Vida Invisible de Addie Larue', 16);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=qWdWzQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'La Vida Invisible de Addie Larue', 16);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/74/9788416517374.jpg', 'La Vida Invisible de Addie Larue', 16);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=-t7WzgEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Un Trato Con El Rey de Los Elfos', 17);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=-t7WzgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Un Trato Con El Rey de Los Elfos', 17);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/95/9788416517695.jpg', 'Un Trato Con El Rey de Los Elfos', 17);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=zhnbzgEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El Atlas de Los Seis', 18);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=zhnbzgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El Atlas de Los Seis', 18);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/17/9788416517817.jpg', 'El Atlas de Los Seis', 18);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/26/9788417248826.jpg', 'Territorios improbables', 19);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=Fl-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Juramentada / Oathbringer', 20);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=Fl-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Juramentada / Oathbringer', 20);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/00/9788417347000.jpg', 'Juramentada / Oathbringer', 20);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OF-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El imperio final / The Final Empire', 21);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OF-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El imperio final / The Final Empire', 21);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/91/9788417347291.jpg', 'El imperio final / The Final Empire', 21);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=LF-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El ritmo de la guerra / Rhythm of War', 22);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=LF-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El ritmo de la guerra / Rhythm of War', 22);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/32/9788417347932.jpg', 'El ritmo de la guerra / Rhythm of War', 22);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/93/9788417517793.jpg', 'Exhalación', 23);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/14/9788418037214.jpg', 'El imperio final', 24);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/76/9788418037276.jpg', 'El pozo de la ascensión', 25);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/90/9788418037290.jpg', 'El héroe de las eras', 26);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/42/9788418037542.jpg', 'Trilogía Fundación (edición ilustrada)', 27);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/57/9788418037757.jpg', 'Escuadrón Cielo: La colección', 28);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=0GGREAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Enhorabuena por tu fracaso / Congratulations On Your Failure', 29);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=0GGREAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Enhorabuena por tu fracaso / Congratulations On Your Failure', 29);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/97/9788418051197.jpg', 'Enhorabuena por tu fracaso / Congratulations On Your Failure', 29);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/58/9788418227158.jpg', 'Un paseo por el mundo', 30);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OLuuzgEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'La cita y otros cuentos de terror', 31);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=OLuuzgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'La cita y otros cuentos de terror', 31);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/12/9788418451812.jpg', 'La cita y otros cuentos de terror', 31);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=q1k6zwEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Sinsonte', 32);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=q1k6zwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Sinsonte', 32);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/71/9788418668371.jpg', 'Sinsonte', 32);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/05/9788419172105.jpg', 'El mapa de las islas', 33);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/70/9788419207470.jpg', 'Roma desordenada', 34);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/97/9788427049697.jpg', 'Academia de Madres, el origen', 35);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/95/9788427049895.jpg', 'Drama Queen', 36);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=0uQizAEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Nuestra parte de noche', 37);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=0uQizAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Nuestra parte de noche', 37);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl9.casadellibro.com/a/l/t5/59/9788433998859.jpg', 'Nuestra parte de noche', 37);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/74/9788445003374.jpg', 'El retorno de Nagash 1', 38);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/98/9788445005798.jpg', 'El libro de los Sith', 39);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/92/9788445006092.jpg', 'La Caída de Gondolin', 40);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/98/9788445006498.jpg', 'Narn i Chîn Húrin', 41);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/06/9788445007006.jpg', 'La rueda del tiempo 1', 42);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/37/9788445007037.jpg', 'El ascenso de la sombra', 43);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/20/9788445009420.jpg', 'Mona Lisa acelerada no 03/03 Trilogía de Sprawl', 44);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/41/9788445011041.jpg', 'Crónicas de la Dragonlance no 01/03 El retorno de los dragones', 45);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl6.casadellibro.com/a/l/t5/96/9788445011096.jpg', 'Elfo Oscuro no 02/03 El exilio', 46);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/02/9788445011102.jpg', 'Crónicas de la Dragonlance no 02/03 La tumba de Huma', 47);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl7.casadellibro.com/a/l/t5/57/9788445011157.jpg', 'Elfo Oscuro no 03/03 El refugio', 48);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/64/9788445011164.jpg', 'Crónicas de la Dragonlance no 03/03 La Reina de la Oscuridad', 49);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/23/9788445012123.jpg', 'La costa más lejana', 50);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/15/9788445012215.jpg', 'Hechicero', 51);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=929BPgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El Silmarillion', 52);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=929BPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El Silmarillion', 52);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/10/9788445073810.jpg', 'El Silmarillion', 52);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=2m-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Sombras de identidad / Shadows of Self', 53);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=2m-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Sombras de identidad / Shadows of Self', 53);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl0.casadellibro.com/a/l/t5/50/9788466658850.jpg', 'Sombras de identidad / Shadows of Self', 53);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=qG-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El pozo de la ascension / The Well of Ascension', 54);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=qG-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El pozo de la ascension / The Well of Ascension', 54);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/04/9788466658904.jpg', 'El pozo de la ascension / The Well of Ascension', 54);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=4G-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'El héroe de las eras / The Hero of Ages', 55);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=4G-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'El héroe de las eras / The Hero of Ages', 55);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/11/9788466658911.jpg', 'El héroe de las eras / The Hero of Ages', 55);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=-G-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Aleación de ley / The Alloy of Law', 56);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=-G-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Aleación de ley / The Alloy of Law', 56);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/28/9788466658928.jpg', 'Aleación de ley / The Alloy of Law', 56);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=7G-REAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Arcanun Ilimitado/ Arcanum Unbounded', 57);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=7G-REAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Arcanun Ilimitado/ Arcanum Unbounded', 57);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl1.casadellibro.com/a/l/t5/21/9788466662321.jpg', 'Arcanun Ilimitado/ Arcanum Unbounded', 57);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=XHSREAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'La caja de botones de Gwendy / Gwendy’s Button Box', 58);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=XHSREAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'La caja de botones de Gwendy / Gwendy’s Button Box', 58);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/18/9788491292418.jpg', 'La caja de botones de Gwendy / Gwendy’s Button Box', 58);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=bh1fQwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Weird tales 1933-1942', 59);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=bh1fQwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Weird tales 1933-1942', 59);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl9.casadellibro.com/a/l/t5/39/9788492492039.jpg', 'Weird tales 1933-1942', 59);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/02/9788492628902.jpg', 'Veinticuatro horas en el Madrid de Galdós', 60);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/44/9788494616044.jpg', 'KAIKI : cuentos de terror y locura', 61);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/48/9788494795848.jpg', 'Hogar', 62);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/95/9788494836695.jpg', 'La maldición de Hill House', 63);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=sqHLcQAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Paura 2', 64);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=sqHLcQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Paura 2', 64);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl4.casadellibro.com/a/l/t5/84/9788496173484.jpg', 'Paura 2', 64);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=rZKxOgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Paura 3 : antología de terror contemporáneo', 65);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=rZKxOgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Paura 3 : antología de terror contemporáneo', 65);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl8.casadellibro.com/a/l/t5/68/9788496173668.jpg', 'Paura 3 : antología de terror contemporáneo', 65);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=nbB-tgAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'La espada del destino', 66);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=nbB-tgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'La espada del destino', 66);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl3.casadellibro.com/a/l/t5/33/9788498890433.jpg', 'La espada del destino', 66);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=BemutwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api', 'Tiempo de odio', 67);
INSERT INTO public.image (url, alt, id_book) VALUES ('http://books.google.com/books/content?id=BemutwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'Tiempo de odio', 67);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl2.casadellibro.com/a/l/t5/32/9788498890532.jpg', 'Tiempo de odio', 67);
INSERT INTO public.image (url, alt, id_book) VALUES ('https://imagessl5.casadellibro.com/a/l/t5/55/9788498891355.jpg', 'LA HISTORIA DE TU VIDA/ STORIES OF YOUR LIFE AND OTHERS.', 68);
