INSERT INTO public.post (created_at, deleted_at, updated_at, book_state, description, image, price, type, id_book, id_user) VALUES
(now(), NULL, now(), 'NUEVO', 'Libro en perfecto estado', 'image_1.jpg', '100.00', 'PURCHASE', 1, 2),
(now(), NULL, now(), 'COMO_NUEVO', 'Apenas usado, como nuevo', 'image_2.jpg', '150.00', 'EXCHANGE', 2, 2),
(now(), NULL, now(), 'MUY_BUENO', 'Libro muy bien cuidado', 'image_3.jpg', '120.00', 'PURCHASE', 3, 3),
(now(), NULL, now(), 'ACEPTABLE', 'Con algunas marcas de uso', 'image_4.jpg', '90.00', 'EXCHANGE', 4, 4),
(now(), NULL, now(), 'BUENO', 'En buen estado general', 'image_5.jpg', '110.00', 'PURCHASE', 5, 5),
(now(), NULL, now(), 'NUEVO', 'Nunca usado, en empaque original', 'image_6.jpg', '200.00', 'EXCHANGE', 6, 6),
(now(), NULL, now(), 'COMO_NUEVO', 'Solo se usó una vez', 'image_7.jpg', '130.00', 'PURCHASE', 7, 7),
(now(), NULL, now(), 'MUY_BUENO', 'Sin marcas ni daños', 'image_8.jpg', '115.00', 'EXCHANGE', 8, 8),
(now(), NULL, now(), 'ACEPTABLE', 'Tiene anotaciones y subrayados', 'image_9.jpg', '85.00', 'PURCHASE', 9, 9),
(now(), NULL, now(), 'BUENO', 'Buen estado para su uso', 'image_10.jpg', '95.00', 'EXCHANGE', 10, 10),
(now(), NULL, now(), 'NUEVO', 'Libro completamente nuevo', 'image_11.jpg', '140.00', 'PURCHASE', 11, 11),
(now(), NULL, now(), 'COMO_NUEVO', 'Parece recién comprado', 'image_12.jpg', '125.00', 'EXCHANGE', 12, 12),
(now(), NULL, now(), 'MUY_BUENO', 'Bien conservado', 'image_13.jpg', '135.00', 'PURCHASE', 13, 13),
(now(), NULL, now(), 'ACEPTABLE', 'Algo desgastado pero usable', 'image_14.jpg', '75.00', 'EXCHANGE', 14, 14),
(now(), NULL, now(), 'BUENO', 'Estado general aceptable', 'image_15.jpg', '105.00', 'PURCHASE', 15, 15),
(now(), NULL, now(), 'NUEVO', 'Casi sin uso', 'image_16.jpg', '160.00', 'EXCHANGE', 16, 16),
(now(), NULL, now(), 'COMO_NUEVO', 'Poco uso, excelente estado', 'image_17.jpg', '155.00', 'PURCHASE', 17, 17),
(now(), NULL, now(), 'MUY_BUENO', 'Muy bien mantenido', 'image_18.jpg', '145.00', 'EXCHANGE', 18, 18),
(now(), NULL, now(), 'ACEPTABLE', 'Con algunas marcas, pero en uso', 'image_19.jpg', '70.00', 'PURCHASE', 19, 19),
(now(), NULL, now(), 'BUENO', 'Buen estado general', 'image_20.jpg', '100.00', 'EXCHANGE', 20, 20);
